[project]
name = "lin-6932-all-computational-models-are-wrong"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "nltk>=3.10.3",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.3",
]
